version: '3.8'

services:
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: mysql-vet
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - veterinaria-network

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: vet-app
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - veterinaria-network

  apache:
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
    container_name: apache-vet
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app
    networks:
      - veterinaria-network

volumes:
  mysql_data:

networks:
  veterinaria-network:
    driver: bridge